---

platform linux

image_resource
  type docker-image
  source {repository czero/cflinuxfs2}

params
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SYSTEM_DATABASE:
  EXTERNAL_MYSQL_HOST:
  EXTERNAL_MYSQL_PORT:
  EXTERNAL_MYSQL_ACCOUNT_USERNAME:
  EXTERNAL_MYSQL_ACCOUNT_PASSWORD:
  EXTERNAL_MYSQL_APP_USAGE_SERVICE_USERNAME:
  EXTERNAL_MYSQL_APP_USAGE_SERVICE_PASSWORD:
  EXTERNAL_MYSQL_AUTOSCALE_USERNAME:
  EXTERNAL_MYSQL_AUTOSCALE_PASSWORD:
  EXTERNAL_MYSQL_CCDB_USERNAME:
  EXTERNAL_MYSQL_CCDB_PASSWORD:
  EXTERNAL_MYSQL_DIEGO_USERNAME:
  EXTERNAL_MYSQL_DIEGO_PASSWORD:
  EXTERNAL_MYSQL_LOCKET_USERNAME:
  EXTERNAL_MYSQL_LOCKET_PASSWORD:
  EXTERNAL_MYSQL_NETWORKPOLICYSERVER_USERNAME:
  EXTERNAL_MYSQL_NETWORKPOLICYSERVER_PASSWORD:
  EXTERNAL_MYSQL_NFSVOLUME_USERNAME:
  EXTERNAL_MYSQL_NFSVOLUME_PASSWORD:
  EXTERNAL_MYSQL_NOTIFICATIONS_USERNAME:
  EXTERNAL_MYSQL_NOTIFICATIONS_PASSWORD:
  EXTERNAL_MYSQL_ROUTING_USERNAME:
  EXTERNAL_MYSQL_ROUTING_PASSWORD:
  EXTERNAL_MYSQL_SILK_USERNAME:
  EXTERNAL_MYSQL_SILK_PASSWORD:
  UAA_DATABASE:
  UAA_DATABASE_HOST:
  UAA_DATABASE_PORT:
  UAA_DATABASE_USERNAME:
  UAA_DATABASE_PASSWORD:
inputs
  - name pcf-pipelines

run
  path pcf-pipelines/tasks/cofigure-external-db/task.sh
